name: DevSecOps End to End pipeline

on:
    push:
        branches: main

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

      
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml
        secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml
    