#this is workflow name
name: Hello

#runs on a trigger
on:
    push: 
        branches: main

#these are jobs inside the workflow
jobs:
        
    #this is name of the job
    greet:
        #this is a github runner, each job runs on a runner
        runs-on:
          - ubuntu-slim
        steps:
            - name: say hellow to users
              run: echo "Hello dosto"

            - name: say hellow to username
              run: echo "Hello $USER"
