name: Hello Rahul

on:
   push:
       branches: main

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: say hello to yourself
              run: echo "Hello Rahul"

            - name: say hello to user
              run: echo "Hello $USER"
                
            
        
